import Head from 'next/head'
import Login from '../container/login'
// import styles from '../styles/Home.module.css'
import HomePage from './home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage/>
    </div>
  )
}
